name: Manual Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本号 (例如: v1.0.0)'
        required: true
        type: string
        default: 'v1.0.0'
      push_to_registry:
        description: '是否推送到 Docker Hub'
        required: true
        type: boolean
        default: true
      update_latest:
        description: '是否同时更新latest标签'
        required: true
        type: boolean
        default: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/baidu-autosave

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: inputs.push_to_registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ inputs.version }}
            type=raw,value=latest,enable=${{ inputs.update_latest }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.push_to_registry }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 